//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.sousCategories = new HashSet<sousCategorie>();
        }
    
        public int codeCAt { get; set; }
        public string nomCat { get; set; }
    
        public virtual ICollection<sousCategorie> sousCategories { get; set; }
    }
}
