//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public Commande()
        {
            this.Msgs = new HashSet<Msg>();
        }
    
        public int idCmd { get; set; }
        public string dateCmd { get; set; }
        public Nullable<int> codeClt { get; set; }
        public Nullable<int> idPrd { get; set; }
        public Nullable<int> qteCmd { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Msg> Msgs { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
