//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sousCategorie
    {
        public sousCategorie()
        {
            this.Produits = new HashSet<Produit>();
        }
    
        public int codeSousCAt { get; set; }
        public string nomSousCat { get; set; }
        public Nullable<int> codeCat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Produit> Produits { get; set; }
    }
}
