//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int idCmd { get; set; }
        public string dateCmd { get; set; }
        public Nullable<int> codeClt { get; set; }
        public Nullable<int> qteCmd { get; set; }
        public string libelle { get; set; }
        public int Stock { get; set; }
        public string image { get; set; }
        public double prix { get; set; }
        public int codeSousCAt { get; set; }
        public string nomSousCat { get; set; }
    }
}
